#ifndef SCALE_FLAGS_H_
#define SCALE_FLAGS_H_

// ONLY LEAVE ONE OF THESE UNCOMMENTED
//#define AVERAGE_SCALE
#define SUBSAMPLE_SCALE

// ONLY UNCOMMENT ONE OF THESE IF USING SUBSAMPLE_SCALE
//#define SUBSAMPLE_SCALE_FACTOR 8
//#define SUBSAMPLE_SCALE_FACTOR 16
//#define SUBSAMPLE_SCALE_FACTOR 32
#define SUBSAMPLE_SCALE_FACTOR 64

#endif
