#ifndef SCALE_FLAGS_H_
#define SCALE_FLAGS_H_

// ONLY LEAVE ONE OF THESE UNCOMMENTED
//#define AVERAGE_SCALE
#define SUBSAMPLE_SCALE

// ONLY UNCOMMENT ONE OF THESE IF USING SUBSAMPLE_SCALE
//#define SUBSAMPLE_SCALE_FACTOR 64
#define SUBSAMPLE_SCALE_FACTOR 256

// ONLY UNCOMMENT ONE OF THESE IF USING SUBSAMPLE_SCALE
#define CPU_SCALE
//#define HW_SCALE

#endif
