// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _subsamble_HH_
#define _subsamble_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "AXIvideo2Mat.h"
#include "Not_r.h"
#include "Mat2AXIvideo.h"
#include "fifo_w8_d1_A.h"
#include "start_for_Not_U0.h"
#include "start_for_Mat2AXIbkb.h"

namespace ap_rtl {

struct subsamble : public sc_module {
    // Port declarations 24
    sc_in< sc_lv<24> > stream_in_TDATA;
    sc_in< sc_lv<3> > stream_in_TKEEP;
    sc_in< sc_lv<3> > stream_in_TSTRB;
    sc_in< sc_lv<1> > stream_in_TUSER;
    sc_in< sc_lv<1> > stream_in_TLAST;
    sc_in< sc_lv<1> > stream_in_TID;
    sc_in< sc_lv<1> > stream_in_TDEST;
    sc_out< sc_lv<24> > stream_process_TDATA;
    sc_out< sc_lv<3> > stream_process_TKEEP;
    sc_out< sc_lv<3> > stream_process_TSTRB;
    sc_out< sc_lv<1> > stream_process_TUSER;
    sc_out< sc_lv<1> > stream_process_TLAST;
    sc_out< sc_lv<1> > stream_process_TID;
    sc_out< sc_lv<1> > stream_process_TDEST;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > stream_in_TVALID;
    sc_out< sc_logic > stream_in_TREADY;
    sc_out< sc_logic > stream_process_TVALID;
    sc_in< sc_logic > stream_process_TREADY;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    subsamble(sc_module_name name);
    SC_HAS_PROCESS(subsamble);

    ~subsamble();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    AXIvideo2Mat* AXIvideo2Mat_U0;
    Not_r* Not_U0;
    Mat2AXIvideo* Mat2AXIvideo_U0;
    fifo_w8_d1_A* img0_data_stream_0_s_U;
    fifo_w8_d1_A* img0_data_stream_1_s_U;
    fifo_w8_d1_A* img0_data_stream_2_s_U;
    fifo_w8_d1_A* img1_data_stream_0_s_U;
    fifo_w8_d1_A* img1_data_stream_1_s_U;
    fifo_w8_d1_A* img1_data_stream_2_s_U;
    start_for_Not_U0* start_for_Not_U0_U;
    start_for_Mat2AXIbkb* start_for_Mat2AXIbkb_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_start;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_done;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_continue;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_idle;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_out;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_stream_in_TREADY;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_0_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_0_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_1_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_1_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_2_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_2_V_write;
    sc_signal< sc_logic > Not_U0_ap_start;
    sc_signal< sc_logic > Not_U0_ap_done;
    sc_signal< sc_logic > Not_U0_ap_continue;
    sc_signal< sc_logic > Not_U0_ap_idle;
    sc_signal< sc_logic > Not_U0_ap_ready;
    sc_signal< sc_logic > Not_U0_start_out;
    sc_signal< sc_logic > Not_U0_start_write;
    sc_signal< sc_logic > Not_U0_src_data_stream_0_V_read;
    sc_signal< sc_logic > Not_U0_src_data_stream_1_V_read;
    sc_signal< sc_logic > Not_U0_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > Not_U0_dst_data_stream_0_V_din;
    sc_signal< sc_logic > Not_U0_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > Not_U0_dst_data_stream_1_V_din;
    sc_signal< sc_logic > Not_U0_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > Not_U0_dst_data_stream_2_V_din;
    sc_signal< sc_logic > Not_U0_dst_data_stream_2_V_write;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_start;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_done;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_continue;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_idle;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_ready;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_0_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_1_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_2_V_read;
    sc_signal< sc_lv<24> > Mat2AXIvideo_U0_stream_process_TDATA;
    sc_signal< sc_logic > Mat2AXIvideo_U0_stream_process_TVALID;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_stream_process_TKEEP;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_stream_process_TSTRB;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_stream_process_TUSER;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_stream_process_TLAST;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_stream_process_TID;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_stream_process_TDEST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > img0_data_stream_0_s_full_n;
    sc_signal< sc_lv<8> > img0_data_stream_0_s_dout;
    sc_signal< sc_logic > img0_data_stream_0_s_empty_n;
    sc_signal< sc_logic > img0_data_stream_1_s_full_n;
    sc_signal< sc_lv<8> > img0_data_stream_1_s_dout;
    sc_signal< sc_logic > img0_data_stream_1_s_empty_n;
    sc_signal< sc_logic > img0_data_stream_2_s_full_n;
    sc_signal< sc_lv<8> > img0_data_stream_2_s_dout;
    sc_signal< sc_logic > img0_data_stream_2_s_empty_n;
    sc_signal< sc_logic > img1_data_stream_0_s_full_n;
    sc_signal< sc_lv<8> > img1_data_stream_0_s_dout;
    sc_signal< sc_logic > img1_data_stream_0_s_empty_n;
    sc_signal< sc_logic > img1_data_stream_1_s_full_n;
    sc_signal< sc_lv<8> > img1_data_stream_1_s_dout;
    sc_signal< sc_logic > img1_data_stream_1_s_empty_n;
    sc_signal< sc_logic > img1_data_stream_2_s_full_n;
    sc_signal< sc_lv<8> > img1_data_stream_2_s_dout;
    sc_signal< sc_logic > img1_data_stream_2_s_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_lv<1> > start_for_Not_U0_din;
    sc_signal< sc_logic > start_for_Not_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Not_U0_dout;
    sc_signal< sc_logic > start_for_Not_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_din;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_dout;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_empty_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_full_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_write;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_AXIvideo2Mat_U0_ap_continue();
    void thread_AXIvideo2Mat_U0_ap_start();
    void thread_Mat2AXIvideo_U0_ap_continue();
    void thread_Mat2AXIvideo_U0_ap_start();
    void thread_Mat2AXIvideo_U0_start_full_n();
    void thread_Mat2AXIvideo_U0_start_write();
    void thread_Not_U0_ap_continue();
    void thread_Not_U0_ap_start();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_start_for_Mat2AXIvideo_U0_din();
    void thread_start_for_Not_U0_din();
    void thread_stream_in_TREADY();
    void thread_stream_process_TDATA();
    void thread_stream_process_TDEST();
    void thread_stream_process_TID();
    void thread_stream_process_TKEEP();
    void thread_stream_process_TLAST();
    void thread_stream_process_TSTRB();
    void thread_stream_process_TUSER();
    void thread_stream_process_TVALID();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
