// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XSUBSAMBLE_H
#define XSUBSAMBLE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xsubsamble_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
    u32 Axilites_r_BaseAddress;
} XSubsamble_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 Axilites_r_BaseAddress;
    u32 IsReady;
} XSubsamble;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XSubsamble_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XSubsamble_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XSubsamble_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XSubsamble_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XSubsamble_Initialize(XSubsamble *InstancePtr, u16 DeviceId);
XSubsamble_Config* XSubsamble_LookupConfig(u16 DeviceId);
int XSubsamble_CfgInitialize(XSubsamble *InstancePtr, XSubsamble_Config *ConfigPtr);
#else
int XSubsamble_Initialize(XSubsamble *InstancePtr, const char* InstanceName);
int XSubsamble_Release(XSubsamble *InstancePtr);
#endif


void XSubsamble_Set_ram(XSubsamble *InstancePtr, u32 Data);
u32 XSubsamble_Get_ram(XSubsamble *InstancePtr);
void XSubsamble_Set_n(XSubsamble *InstancePtr, u32 Data);
u32 XSubsamble_Get_n(XSubsamble *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
