// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xsubsamplesection.h"

extern XSubsamplesection_Config XSubsamplesection_ConfigTable[];

XSubsamplesection_Config *XSubsamplesection_LookupConfig(u16 DeviceId) {
	XSubsamplesection_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XSUBSAMPLESECTION_NUM_INSTANCES; Index++) {
		if (XSubsamplesection_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XSubsamplesection_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XSubsamplesection_Initialize(XSubsamplesection *InstancePtr, u16 DeviceId) {
	XSubsamplesection_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XSubsamplesection_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XSubsamplesection_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

