// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Filter2D (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_src_data_stream_0_V_dout,
        p_src_data_stream_0_V_empty_n,
        p_src_data_stream_0_V_read,
        p_src_data_stream_1_V_dout,
        p_src_data_stream_1_V_empty_n,
        p_src_data_stream_1_V_read,
        p_src_data_stream_2_V_dout,
        p_src_data_stream_2_V_empty_n,
        p_src_data_stream_2_V_read,
        p_dst_data_stream_0_V_din,
        p_dst_data_stream_0_V_full_n,
        p_dst_data_stream_0_V_write,
        p_dst_data_stream_1_V_din,
        p_dst_data_stream_1_V_full_n,
        p_dst_data_stream_1_V_write,
        p_dst_data_stream_2_V_din,
        p_dst_data_stream_2_V_full_n,
        p_dst_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state7 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_data_stream_0_V_dout;
input   p_src_data_stream_0_V_empty_n;
output   p_src_data_stream_0_V_read;
input  [7:0] p_src_data_stream_1_V_dout;
input   p_src_data_stream_1_V_empty_n;
output   p_src_data_stream_1_V_read;
input  [7:0] p_src_data_stream_2_V_dout;
input   p_src_data_stream_2_V_empty_n;
output   p_src_data_stream_2_V_read;
output  [7:0] p_dst_data_stream_0_V_din;
input   p_dst_data_stream_0_V_full_n;
output   p_dst_data_stream_0_V_write;
output  [7:0] p_dst_data_stream_1_V_din;
input   p_dst_data_stream_1_V_full_n;
output   p_dst_data_stream_1_V_write;
output  [7:0] p_dst_data_stream_2_V_din;
input   p_dst_data_stream_2_V_full_n;
output   p_dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_data_stream_0_V_read;
reg p_src_data_stream_1_V_read;
reg p_src_data_stream_2_V_read;
reg p_dst_data_stream_0_V_write;
reg p_dst_data_stream_1_V_write;
reg p_dst_data_stream_2_V_write;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_reg_2570;
reg   [0:0] or_cond_i_i_reg_2579;
reg   [0:0] icmp_reg_2519;
reg   [0:0] tmp_1_reg_2510;
reg    p_src_data_stream_1_V_blk_n;
reg    p_src_data_stream_2_V_blk_n;
reg    p_dst_data_stream_0_V_blk_n;
reg    ap_enable_reg_pp0_iter2;
reg   [0:0] or_cond_i_reg_2619;
reg   [0:0] or_cond_i_reg_2619_pp0_iter1_reg;
reg    p_dst_data_stream_1_V_blk_n;
reg    p_dst_data_stream_2_V_blk_n;
reg   [10:0] t_V_2_reg_598;
wire   [1:0] tmp_6_fu_609_p2;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond1_fu_625_p2;
wire    ap_CS_fsm_state3;
wire   [10:0] i_V_fu_631_p2;
reg   [10:0] i_V_reg_2505;
wire   [0:0] tmp_1_fu_637_p2;
wire   [0:0] tmp_73_0_0_not_fu_643_p2;
reg   [0:0] tmp_73_0_0_not_reg_2514;
wire   [0:0] icmp_fu_659_p2;
wire   [0:0] tmp_9_fu_665_p2;
reg   [0:0] tmp_9_reg_2524;
wire   [0:0] tmp_117_0_1_fu_671_p2;
reg   [0:0] tmp_117_0_1_reg_2528;
wire   [0:0] tmp_2_fu_677_p2;
reg   [0:0] tmp_2_reg_2532;
wire   [1:0] row_assign_9_fu_837_p2;
reg   [1:0] row_assign_9_reg_2545;
wire   [1:0] row_assign_9_0_1_t_fu_875_p2;
reg   [1:0] row_assign_9_0_1_t_reg_2550;
wire   [1:0] row_assign_9_0_2_t_fu_913_p2;
reg   [1:0] row_assign_9_0_2_t_reg_2557;
wire   [1:0] row_assign_9_1_0_t_fu_945_p2;
reg   [1:0] row_assign_9_1_0_t_reg_2564;
wire   [0:0] exitcond_fu_955_p2;
wire    ap_block_state4_pp0_stage0_iter0;
reg    ap_predicate_op217_read_state5;
reg    ap_predicate_op229_read_state5;
reg    ap_predicate_op275_read_state5;
reg    ap_predicate_op287_read_state5;
reg    ap_predicate_op330_read_state5;
reg    ap_predicate_op339_read_state5;
reg    ap_block_state5_pp0_stage0_iter1;
reg    ap_block_state6_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_11001;
wire   [10:0] j_V_fu_961_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] or_cond_i_i_fu_1009_p2;
wire   [1:0] tmp_67_fu_1069_p1;
reg   [1:0] tmp_67_reg_2583;
wire   [0:0] brmerge_fu_1073_p2;
reg   [0:0] brmerge_reg_2588;
reg   [10:0] k_buf_0_val_3_addr_reg_2601;
reg   [10:0] k_buf_0_val_4_addr_reg_2607;
reg   [10:0] k_buf_0_val_5_addr_reg_2613;
wire   [0:0] or_cond_i_fu_1091_p2;
reg   [10:0] k_buf_1_val_3_addr_reg_2623;
reg   [10:0] k_buf_1_val_4_addr_reg_2629;
reg   [10:0] k_buf_1_val_5_addr_reg_2635;
reg   [10:0] k_buf_2_val_3_addr_reg_2641;
reg   [10:0] k_buf_2_val_4_addr_reg_2647;
reg   [10:0] k_buf_2_val_5_addr_reg_2653;
wire   [7:0] src_kernel_win_0_va_7_fu_1253_p3;
reg   [7:0] src_kernel_win_0_va_7_reg_2659;
wire   [9:0] sum2_fu_1327_p2;
reg   [9:0] sum2_reg_2665;
wire   [8:0] tmp6_fu_1333_p2;
reg   [8:0] tmp6_reg_2670;
wire   [7:0] tmp7_fu_1345_p2;
reg   [7:0] tmp7_reg_2675;
wire   [7:0] tmp10_fu_1351_p2;
reg   [7:0] tmp10_reg_2680;
wire   [7:0] src_kernel_win_1_va_7_fu_1500_p3;
reg   [7:0] src_kernel_win_1_va_7_reg_2685;
wire   [9:0] sum4_fu_1574_p2;
reg   [9:0] sum4_reg_2691;
wire   [8:0] tmp17_fu_1580_p2;
reg   [8:0] tmp17_reg_2696;
wire   [7:0] tmp18_fu_1592_p2;
reg   [7:0] tmp18_reg_2701;
wire   [7:0] tmp21_fu_1598_p2;
reg   [7:0] tmp21_reg_2706;
wire   [7:0] src_kernel_win_2_va_10_fu_1729_p3;
reg   [7:0] src_kernel_win_2_va_10_reg_2711;
wire   [9:0] sum5_fu_1803_p2;
reg   [9:0] sum5_reg_2717;
wire   [8:0] tmp28_fu_1809_p2;
reg   [8:0] tmp28_reg_2722;
wire   [7:0] tmp29_fu_1821_p2;
reg   [7:0] tmp29_reg_2727;
wire   [7:0] tmp32_fu_1827_p2;
reg   [7:0] tmp32_reg_2732;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter1_state5;
wire   [10:0] k_buf_0_val_3_address0;
reg    k_buf_0_val_3_ce0;
wire   [7:0] k_buf_0_val_3_q0;
reg    k_buf_0_val_3_ce1;
reg    k_buf_0_val_3_we1;
wire   [10:0] k_buf_0_val_4_address0;
reg    k_buf_0_val_4_ce0;
wire   [7:0] k_buf_0_val_4_q0;
reg    k_buf_0_val_4_ce1;
reg    k_buf_0_val_4_we1;
reg   [7:0] k_buf_0_val_4_d1;
wire   [10:0] k_buf_0_val_5_address0;
reg    k_buf_0_val_5_ce0;
wire   [7:0] k_buf_0_val_5_q0;
reg    k_buf_0_val_5_ce1;
reg    k_buf_0_val_5_we1;
reg   [7:0] k_buf_0_val_5_d1;
wire   [10:0] k_buf_1_val_3_address0;
reg    k_buf_1_val_3_ce0;
wire   [7:0] k_buf_1_val_3_q0;
reg    k_buf_1_val_3_ce1;
reg    k_buf_1_val_3_we1;
wire   [10:0] k_buf_1_val_4_address0;
reg    k_buf_1_val_4_ce0;
wire   [7:0] k_buf_1_val_4_q0;
reg    k_buf_1_val_4_ce1;
reg    k_buf_1_val_4_we1;
reg   [7:0] k_buf_1_val_4_d1;
wire   [10:0] k_buf_1_val_5_address0;
reg    k_buf_1_val_5_ce0;
wire   [7:0] k_buf_1_val_5_q0;
reg    k_buf_1_val_5_ce1;
reg    k_buf_1_val_5_we1;
reg   [7:0] k_buf_1_val_5_d1;
wire   [10:0] k_buf_2_val_3_address0;
reg    k_buf_2_val_3_ce0;
wire   [7:0] k_buf_2_val_3_q0;
reg    k_buf_2_val_3_ce1;
reg    k_buf_2_val_3_we1;
wire   [10:0] k_buf_2_val_4_address0;
reg    k_buf_2_val_4_ce0;
wire   [7:0] k_buf_2_val_4_q0;
reg    k_buf_2_val_4_ce1;
reg    k_buf_2_val_4_we1;
reg   [7:0] k_buf_2_val_4_d1;
wire   [10:0] k_buf_2_val_5_address0;
reg    k_buf_2_val_5_ce0;
wire   [7:0] k_buf_2_val_5_q0;
reg    k_buf_2_val_5_ce1;
reg    k_buf_2_val_5_we1;
reg   [7:0] k_buf_2_val_5_d1;
reg   [1:0] tmp_5_reg_576;
wire   [0:0] tmp_7_fu_615_p2;
reg   [10:0] t_V_reg_587;
wire    ap_CS_fsm_state7;
wire   [63:0] tmp_25_fu_1078_p1;
reg    ap_block_pp0_stage0_01001;
reg   [7:0] src_kernel_win_0_va_fu_234;
wire   [7:0] src_kernel_win_0_va_6_fu_1235_p3;
reg   [7:0] src_kernel_win_0_va_1_fu_238;
reg   [7:0] src_kernel_win_0_va_2_fu_242;
reg   [7:0] src_kernel_win_0_va_3_fu_246;
reg   [7:0] src_kernel_win_0_va_4_fu_250;
wire   [7:0] src_kernel_win_0_va_8_fu_1271_p3;
reg   [7:0] src_kernel_win_0_va_5_fu_254;
reg   [7:0] src_kernel_win_1_va_fu_258;
wire   [7:0] src_kernel_win_1_va_6_fu_1482_p3;
reg   [7:0] src_kernel_win_1_va_1_fu_262;
reg   [7:0] src_kernel_win_1_va_2_fu_266;
reg   [7:0] src_kernel_win_1_va_3_fu_270;
reg   [7:0] src_kernel_win_1_va_4_fu_274;
wire   [7:0] src_kernel_win_1_va_8_fu_1518_p3;
reg   [7:0] src_kernel_win_1_va_5_fu_278;
reg   [7:0] src_kernel_win_2_va_fu_282;
wire   [7:0] src_kernel_win_2_va_9_fu_1711_p3;
reg   [7:0] src_kernel_win_2_va_1_fu_286;
reg   [7:0] src_kernel_win_2_va_2_fu_290;
reg   [7:0] src_kernel_win_2_va_3_fu_294;
reg   [7:0] src_kernel_win_2_va_4_fu_298;
wire   [7:0] src_kernel_win_2_va_11_fu_1747_p3;
reg   [7:0] src_kernel_win_2_va_5_fu_302;
reg   [7:0] right_border_buf_0_s_fu_306;
wire   [7:0] col_buf_0_val_0_0_fu_1140_p3;
reg   [7:0] right_border_buf_0_1_fu_310;
reg   [7:0] right_border_buf_2_s_fu_314;
reg   [7:0] right_border_buf_0_2_fu_318;
wire   [7:0] col_buf_0_val_1_0_fu_1159_p3;
reg   [7:0] right_border_buf_0_3_fu_322;
reg   [7:0] right_border_buf_2_1_fu_326;
wire   [7:0] col_buf_2_val_2_0_fu_1663_p3;
reg   [7:0] right_border_buf_0_4_fu_330;
wire   [7:0] col_buf_0_val_2_0_fu_1178_p3;
reg   [7:0] right_border_buf_0_5_fu_334;
reg   [7:0] right_border_buf_2_2_fu_338;
reg   [7:0] right_border_buf_1_s_fu_342;
wire   [7:0] col_buf_1_val_0_0_fu_1387_p3;
reg   [7:0] right_border_buf_1_1_fu_346;
reg   [7:0] right_border_buf_2_3_fu_350;
wire   [7:0] col_buf_2_val_1_0_fu_1644_p3;
reg   [7:0] right_border_buf_1_2_fu_354;
wire   [7:0] col_buf_1_val_1_0_fu_1406_p3;
reg   [7:0] right_border_buf_1_3_fu_358;
reg   [7:0] right_border_buf_2_4_fu_362;
reg   [7:0] right_border_buf_1_4_fu_366;
wire   [7:0] col_buf_1_val_2_0_fu_1425_p3;
reg   [7:0] right_border_buf_1_5_fu_370;
reg   [7:0] right_border_buf_2_5_fu_374;
wire   [7:0] col_buf_2_val_0_0_fu_1625_p3;
wire   [9:0] tmp_fu_649_p4;
wire   [11:0] t_V_cast_fu_621_p1;
wire   [11:0] tmp_3_fu_683_p2;
wire   [0:0] tmp_10_fu_689_p3;
wire   [0:0] tmp_4_fu_703_p2;
wire   [0:0] rev_fu_697_p2;
wire   [0:0] tmp_11_fu_715_p3;
wire   [11:0] p_assign_7_fu_723_p2;
wire   [11:0] p_p2_i413_i_fu_729_p3;
wire   [11:0] p_assign_6_0_1_fu_753_p2;
wire   [11:0] p_assign_6_0_2_fu_779_p2;
wire   [11:0] p_assign_8_fu_743_p2;
wire   [0:0] tmp_8_fu_737_p2;
wire   [1:0] tmp_30_fu_813_p1;
wire   [1:0] tmp_31_fu_817_p1;
wire   [0:0] or_cond_i412_i_fu_709_p2;
wire   [1:0] tmp_24_fu_809_p1;
wire   [1:0] tmp_38_fu_821_p3;
wire   [1:0] tmp_39_fu_829_p3;
wire   [1:0] tmp_12_fu_749_p1;
wire   [1:0] tmp_16_fu_775_p1;
wire   [0:0] tmp_15_fu_767_p3;
wire   [1:0] tmp_41_fu_849_p2;
wire   [1:0] tmp_45_fu_855_p1;
wire   [0:0] tmp_13_fu_759_p3;
wire   [1:0] tmp_35_fu_859_p3;
wire   [1:0] tmp_22_fu_843_p2;
wire   [1:0] tmp_32_fu_867_p3;
wire   [1:0] tmp_20_fu_801_p1;
wire   [0:0] tmp_19_fu_793_p3;
wire   [1:0] tmp_48_fu_887_p2;
wire   [1:0] tmp_53_fu_893_p1;
wire   [0:0] tmp_18_fu_785_p3;
wire   [1:0] tmp_54_fu_897_p3;
wire   [1:0] tmp_34_fu_881_p2;
wire   [1:0] tmp_36_fu_905_p3;
wire   [1:0] tmp_21_fu_805_p1;
wire   [1:0] tmp_46_fu_919_p2;
wire   [1:0] tmp_56_fu_933_p1;
wire   [1:0] tmp_47_fu_925_p3;
wire   [1:0] tmp_49_fu_937_p3;
wire   [9:0] tmp_63_fu_967_p4;
wire   [11:0] t_V_2_cast_fu_951_p1;
wire   [11:0] ImagLoc_x_fu_983_p2;
wire   [0:0] tmp_64_fu_989_p3;
wire   [0:0] tmp_17_fu_1003_p2;
wire   [0:0] rev1_fu_997_p2;
wire   [0:0] tmp_66_fu_1015_p3;
wire   [11:0] p_assign_1_fu_1023_p2;
wire   [11:0] p_p2_i_i_fu_1029_p3;
wire   [0:0] tmp_23_fu_1037_p2;
wire   [11:0] p_assign_2_fu_1043_p2;
wire   [11:0] p_p2_i_i_p_assign_2_fu_1049_p3;
wire  signed [11:0] x_fu_1057_p3;
wire  signed [31:0] x_cast_fu_1065_p1;
wire   [0:0] icmp1_fu_977_p2;
wire   [1:0] col_assign_2_0_t_fu_1123_p2;
wire   [7:0] tmp_26_fu_1128_p5;
wire   [7:0] tmp_27_fu_1147_p5;
wire   [7:0] tmp_28_fu_1166_p5;
wire   [7:0] tmp_29_fu_1224_p5;
wire   [7:0] tmp_33_fu_1242_p5;
wire   [7:0] tmp_37_fu_1260_p5;
wire   [8:0] p_shl_fu_1295_p3;
wire   [9:0] p_shl_cast_fu_1303_p1;
wire   [9:0] OP1_V_0_2_cast_fu_1313_p1;
wire   [9:0] OP1_V_0_cast_fu_1287_p1;
wire   [9:0] sum1_fu_1321_p2;
wire   [8:0] tmp_161_0_2_2_cast_fu_1317_p1;
wire   [8:0] tmp_161_0_0_2_cast_fu_1291_p1;
wire   [7:0] tmp_70_fu_1307_p2;
wire   [7:0] tmp8_fu_1339_p2;
wire   [7:0] tmp_42_fu_1375_p5;
wire   [7:0] tmp_43_fu_1394_p5;
wire   [7:0] tmp_44_fu_1413_p5;
wire   [7:0] tmp_50_fu_1471_p5;
wire   [7:0] tmp_51_fu_1489_p5;
wire   [7:0] tmp_52_fu_1507_p5;
wire   [8:0] p_shl1_fu_1542_p3;
wire   [9:0] p_shl1_cast_fu_1550_p1;
wire   [9:0] OP1_V_1_2_cast_fu_1560_p1;
wire   [9:0] OP1_V_1_cast_fu_1534_p1;
wire   [9:0] sum3_fu_1568_p2;
wire   [8:0] tmp_161_1_2_2_cast_fu_1564_p1;
wire   [8:0] tmp_161_1_0_2_cast_fu_1538_p1;
wire   [7:0] tmp_76_fu_1554_p2;
wire   [7:0] tmp19_fu_1586_p2;
wire   [7:0] tmp_57_fu_1613_p5;
wire   [7:0] tmp_58_fu_1632_p5;
wire   [7:0] tmp_59_fu_1651_p5;
wire   [7:0] tmp_60_fu_1700_p5;
wire   [7:0] tmp_61_fu_1718_p5;
wire   [7:0] tmp_62_fu_1736_p5;
wire   [8:0] p_shl2_fu_1771_p3;
wire   [9:0] p_shl2_cast_fu_1779_p1;
wire   [9:0] OP1_V_2_2_cast_fu_1789_p1;
wire   [9:0] OP1_V_2_cast_fu_1763_p1;
wire   [9:0] sum_fu_1797_p2;
wire   [8:0] tmp_161_2_2_2_cast_fu_1793_p1;
wire   [8:0] tmp_161_2_0_2_cast_fu_1767_p1;
wire   [7:0] tmp_82_fu_1783_p2;
wire   [7:0] tmp30_fu_1815_p2;
wire   [8:0] r_V_7_0_1_2_fu_1950_p3;
wire   [9:0] tmp_161_0_1_cast_fu_1957_p1;
wire   [9:0] tmp6_cast_fu_1969_p1;
wire   [9:0] tmp5_fu_1972_p2;
wire   [10:0] tmp5_cast_fu_1978_p1;
wire   [10:0] sum40_cast_fu_1966_p1;
wire   [10:0] p_Val2_2_fu_1982_p2;
wire   [7:0] tmp_71_fu_1961_p2;
wire   [7:0] tmp9_fu_1996_p2;
wire   [0:0] isneg_fu_1988_p3;
wire   [2:0] tmp_40_fu_2006_p4;
wire   [0:0] not_i_i_i_fu_2022_p2;
wire   [0:0] tmp_i_i_fu_2016_p2;
wire   [0:0] overflow_fu_2028_p2;
wire   [0:0] tmp_i_i_72_fu_2042_p2;
wire   [7:0] p_mux_i_i_cast_fu_2034_p3;
wire   [7:0] p_Val2_1_fu_2001_p2;
wire   [8:0] r_V_7_1_1_2_fu_2057_p3;
wire   [9:0] tmp_161_1_1_cast_fu_2064_p1;
wire   [9:0] tmp17_cast_fu_2076_p1;
wire   [9:0] tmp16_fu_2079_p2;
wire   [10:0] tmp16_cast_fu_2085_p1;
wire   [10:0] sum37_cast_fu_2073_p1;
wire   [10:0] p_Val2_5_fu_2089_p2;
wire   [7:0] tmp_77_fu_2068_p2;
wire   [7:0] tmp20_fu_2103_p2;
wire   [0:0] isneg_1_fu_2095_p3;
wire   [2:0] tmp_55_fu_2113_p4;
wire   [0:0] not_i_i_i1_fu_2129_p2;
wire   [0:0] tmp_i_i1_fu_2123_p2;
wire   [0:0] overflow_1_fu_2135_p2;
wire   [0:0] tmp_i_i1_73_fu_2149_p2;
wire   [7:0] p_mux_i_i1_cast_fu_2141_p3;
wire   [7:0] p_Val2_3_fu_2108_p2;
wire   [8:0] r_V_7_2_1_2_fu_2164_p3;
wire   [9:0] tmp_161_2_1_cast_fu_2171_p1;
wire   [9:0] tmp28_cast_fu_2183_p1;
wire   [9:0] tmp27_fu_2186_p2;
wire   [10:0] tmp27_cast_fu_2192_p1;
wire   [10:0] sum34_cast_fu_2180_p1;
wire   [10:0] p_Val2_s_fu_2196_p2;
wire   [7:0] tmp_83_fu_2175_p2;
wire   [7:0] tmp31_fu_2210_p2;
wire   [0:0] isneg_2_fu_2202_p3;
wire   [2:0] tmp_65_fu_2220_p4;
wire   [0:0] not_i_i_i2_fu_2236_p2;
wire   [0:0] tmp_i_i2_fu_2230_p2;
wire   [0:0] overflow_2_fu_2242_p2;
wire   [0:0] tmp_i_i2_74_fu_2256_p2;
wire   [7:0] p_mux_i_i2_cast_fu_2248_p3;
wire   [7:0] p_Val2_6_fu_2215_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_554;
reg    ap_condition_62;
reg    ap_condition_548;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_0_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_3_address0),
    .ce0(k_buf_0_val_3_ce0),
    .q0(k_buf_0_val_3_q0),
    .address1(k_buf_0_val_3_addr_reg_2601),
    .ce1(k_buf_0_val_3_ce1),
    .we1(k_buf_0_val_3_we1),
    .d1(p_src_data_stream_0_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_0_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_4_address0),
    .ce0(k_buf_0_val_4_ce0),
    .q0(k_buf_0_val_4_q0),
    .address1(k_buf_0_val_4_addr_reg_2607),
    .ce1(k_buf_0_val_4_ce1),
    .we1(k_buf_0_val_4_we1),
    .d1(k_buf_0_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_0_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_0_val_5_address0),
    .ce0(k_buf_0_val_5_ce0),
    .q0(k_buf_0_val_5_q0),
    .address1(k_buf_0_val_5_addr_reg_2613),
    .ce1(k_buf_0_val_5_ce1),
    .we1(k_buf_0_val_5_we1),
    .d1(k_buf_0_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_1_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_3_address0),
    .ce0(k_buf_1_val_3_ce0),
    .q0(k_buf_1_val_3_q0),
    .address1(k_buf_1_val_3_addr_reg_2623),
    .ce1(k_buf_1_val_3_ce1),
    .we1(k_buf_1_val_3_we1),
    .d1(p_src_data_stream_1_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_1_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_4_address0),
    .ce0(k_buf_1_val_4_ce0),
    .q0(k_buf_1_val_4_q0),
    .address1(k_buf_1_val_4_addr_reg_2629),
    .ce1(k_buf_1_val_4_ce1),
    .we1(k_buf_1_val_4_we1),
    .d1(k_buf_1_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_1_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_1_val_5_address0),
    .ce0(k_buf_1_val_5_ce0),
    .q0(k_buf_1_val_5_q0),
    .address1(k_buf_1_val_5_addr_reg_2635),
    .ce1(k_buf_1_val_5_ce1),
    .we1(k_buf_1_val_5_we1),
    .d1(k_buf_1_val_5_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_2_val_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_3_address0),
    .ce0(k_buf_2_val_3_ce0),
    .q0(k_buf_2_val_3_q0),
    .address1(k_buf_2_val_3_addr_reg_2641),
    .ce1(k_buf_2_val_3_ce1),
    .we1(k_buf_2_val_3_we1),
    .d1(p_src_data_stream_2_V_dout)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_2_val_4_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_4_address0),
    .ce0(k_buf_2_val_4_ce0),
    .q0(k_buf_2_val_4_q0),
    .address1(k_buf_2_val_4_addr_reg_2647),
    .ce1(k_buf_2_val_4_ce1),
    .we1(k_buf_2_val_4_we1),
    .d1(k_buf_2_val_4_d1)
);

Filter2D_k_buf_0_eOg #(
    .DataWidth( 8 ),
    .AddressRange( 1680 ),
    .AddressWidth( 11 ))
k_buf_2_val_5_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(k_buf_2_val_5_address0),
    .ce0(k_buf_2_val_5_ce0),
    .q0(k_buf_2_val_5_q0),
    .address1(k_buf_2_val_5_addr_reg_2653),
    .ce1(k_buf_2_val_5_ce1),
    .we1(k_buf_2_val_5_we1),
    .d1(k_buf_2_val_5_d1)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U23(
    .din0(right_border_buf_0_s_fu_306),
    .din1(right_border_buf_0_1_fu_310),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_26_fu_1128_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U24(
    .din0(right_border_buf_0_2_fu_318),
    .din1(right_border_buf_0_3_fu_322),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_27_fu_1147_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U25(
    .din0(right_border_buf_0_4_fu_330),
    .din1(right_border_buf_0_5_fu_334),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_28_fu_1166_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U26(
    .din0(col_buf_0_val_0_0_fu_1140_p3),
    .din1(col_buf_0_val_1_0_fu_1159_p3),
    .din2(col_buf_0_val_2_0_fu_1178_p3),
    .din3(row_assign_9_reg_2545),
    .dout(tmp_29_fu_1224_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U27(
    .din0(col_buf_0_val_0_0_fu_1140_p3),
    .din1(col_buf_0_val_1_0_fu_1159_p3),
    .din2(col_buf_0_val_2_0_fu_1178_p3),
    .din3(row_assign_9_0_1_t_reg_2550),
    .dout(tmp_33_fu_1242_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U28(
    .din0(col_buf_0_val_0_0_fu_1140_p3),
    .din1(col_buf_0_val_1_0_fu_1159_p3),
    .din2(col_buf_0_val_2_0_fu_1178_p3),
    .din3(row_assign_9_0_2_t_reg_2557),
    .dout(tmp_37_fu_1260_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U29(
    .din0(right_border_buf_1_s_fu_342),
    .din1(right_border_buf_1_1_fu_346),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_42_fu_1375_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U30(
    .din0(right_border_buf_1_2_fu_354),
    .din1(right_border_buf_1_3_fu_358),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_43_fu_1394_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U31(
    .din0(right_border_buf_1_4_fu_366),
    .din1(right_border_buf_1_5_fu_370),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_44_fu_1413_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U32(
    .din0(col_buf_1_val_0_0_fu_1387_p3),
    .din1(col_buf_1_val_1_0_fu_1406_p3),
    .din2(col_buf_1_val_2_0_fu_1425_p3),
    .din3(row_assign_9_1_0_t_reg_2564),
    .dout(tmp_50_fu_1471_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U33(
    .din0(col_buf_1_val_0_0_fu_1387_p3),
    .din1(col_buf_1_val_1_0_fu_1406_p3),
    .din2(col_buf_1_val_2_0_fu_1425_p3),
    .din3(row_assign_9_0_1_t_reg_2550),
    .dout(tmp_51_fu_1489_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U34(
    .din0(col_buf_1_val_0_0_fu_1387_p3),
    .din1(col_buf_1_val_1_0_fu_1406_p3),
    .din2(col_buf_1_val_2_0_fu_1425_p3),
    .din3(row_assign_9_0_2_t_reg_2557),
    .dout(tmp_52_fu_1507_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U35(
    .din0(right_border_buf_2_5_fu_374),
    .din1(right_border_buf_2_4_fu_362),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_57_fu_1613_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U36(
    .din0(right_border_buf_2_3_fu_350),
    .din1(right_border_buf_2_2_fu_338),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_58_fu_1632_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U37(
    .din0(right_border_buf_2_1_fu_326),
    .din1(right_border_buf_2_s_fu_314),
    .din2(8'd0),
    .din3(col_assign_2_0_t_fu_1123_p2),
    .dout(tmp_59_fu_1651_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U38(
    .din0(col_buf_2_val_0_0_fu_1625_p3),
    .din1(col_buf_2_val_1_0_fu_1644_p3),
    .din2(col_buf_2_val_2_0_fu_1663_p3),
    .din3(row_assign_9_1_0_t_reg_2564),
    .dout(tmp_60_fu_1700_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U39(
    .din0(col_buf_2_val_0_0_fu_1625_p3),
    .din1(col_buf_2_val_1_0_fu_1644_p3),
    .din2(col_buf_2_val_2_0_fu_1663_p3),
    .din3(row_assign_9_0_1_t_reg_2550),
    .dout(tmp_61_fu_1718_p5)
);

subsamble_mux_32_ncg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
subsamble_mux_32_ncg_U40(
    .din0(col_buf_2_val_0_0_fu_1625_p3),
    .din1(col_buf_2_val_1_0_fu_1644_p3),
    .din2(col_buf_2_val_2_0_fu_1663_p3),
    .din3(row_assign_9_0_2_t_reg_2557),
    .dout(tmp_62_fu_1736_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((exitcond_fu_955_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond1_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5)) | ((exitcond1_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter1_state5))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((exitcond1_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_955_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_598 <= j_V_fu_961_p2;
    end else if (((exitcond1_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        t_V_2_reg_598 <= 11'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_fu_615_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_reg_587 <= 11'd0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        t_V_reg_587 <= i_V_reg_2505;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        tmp_5_reg_576 <= 2'd0;
    end else if (((tmp_7_fu_615_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_5_reg_576 <= tmp_6_fu_609_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_fu_955_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        brmerge_reg_2588 <= brmerge_fu_1073_p2;
        k_buf_0_val_3_addr_reg_2601 <= tmp_25_fu_1078_p1;
        k_buf_0_val_4_addr_reg_2607 <= tmp_25_fu_1078_p1;
        k_buf_0_val_5_addr_reg_2613 <= tmp_25_fu_1078_p1;
        k_buf_1_val_3_addr_reg_2623 <= tmp_25_fu_1078_p1;
        k_buf_1_val_4_addr_reg_2629 <= tmp_25_fu_1078_p1;
        k_buf_1_val_5_addr_reg_2635 <= tmp_25_fu_1078_p1;
        k_buf_2_val_3_addr_reg_2641 <= tmp_25_fu_1078_p1;
        k_buf_2_val_4_addr_reg_2647 <= tmp_25_fu_1078_p1;
        k_buf_2_val_5_addr_reg_2653 <= tmp_25_fu_1078_p1;
        or_cond_i_i_reg_2579 <= or_cond_i_i_fu_1009_p2;
        or_cond_i_reg_2619 <= or_cond_i_fu_1091_p2;
        tmp_67_reg_2583 <= tmp_67_fu_1069_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_reg_2570 <= exitcond_fu_955_p2;
        or_cond_i_reg_2619_pp0_iter1_reg <= or_cond_i_reg_2619;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        i_V_reg_2505 <= i_V_fu_631_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_625_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        icmp_reg_2519 <= icmp_fu_659_p2;
        row_assign_9_0_1_t_reg_2550 <= row_assign_9_0_1_t_fu_875_p2;
        row_assign_9_0_2_t_reg_2557 <= row_assign_9_0_2_t_fu_913_p2;
        row_assign_9_1_0_t_reg_2564 <= row_assign_9_1_0_t_fu_945_p2;
        row_assign_9_reg_2545 <= row_assign_9_fu_837_p2;
        tmp_117_0_1_reg_2528 <= tmp_117_0_1_fu_671_p2;
        tmp_1_reg_2510 <= tmp_1_fu_637_p2;
        tmp_2_reg_2532 <= tmp_2_fu_677_p2;
        tmp_73_0_0_not_reg_2514 <= tmp_73_0_0_not_fu_643_p2;
        tmp_9_reg_2524 <= tmp_9_fu_665_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1))) begin
        right_border_buf_0_1_fu_310 <= right_border_buf_0_s_fu_306;
        right_border_buf_0_2_fu_318 <= col_buf_0_val_1_0_fu_1159_p3;
        right_border_buf_0_3_fu_322 <= right_border_buf_0_2_fu_318;
        right_border_buf_0_4_fu_330 <= col_buf_0_val_2_0_fu_1178_p3;
        right_border_buf_0_5_fu_334 <= right_border_buf_0_4_fu_330;
        right_border_buf_0_s_fu_306 <= col_buf_0_val_0_0_fu_1140_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1))) begin
        right_border_buf_1_1_fu_346 <= right_border_buf_1_s_fu_342;
        right_border_buf_1_2_fu_354 <= col_buf_1_val_1_0_fu_1406_p3;
        right_border_buf_1_3_fu_358 <= right_border_buf_1_2_fu_354;
        right_border_buf_1_4_fu_366 <= col_buf_1_val_2_0_fu_1425_p3;
        right_border_buf_1_5_fu_370 <= right_border_buf_1_4_fu_366;
        right_border_buf_1_s_fu_342 <= col_buf_1_val_0_0_fu_1387_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1))) begin
        right_border_buf_2_1_fu_326 <= col_buf_2_val_2_0_fu_1663_p3;
        right_border_buf_2_2_fu_338 <= right_border_buf_2_3_fu_350;
        right_border_buf_2_3_fu_350 <= col_buf_2_val_1_0_fu_1644_p3;
        right_border_buf_2_4_fu_362 <= right_border_buf_2_5_fu_374;
        right_border_buf_2_5_fu_374 <= col_buf_2_val_0_0_fu_1625_p3;
        right_border_buf_2_s_fu_314 <= right_border_buf_2_1_fu_326;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_1_fu_238 <= src_kernel_win_0_va_fu_234;
        src_kernel_win_0_va_2_fu_242 <= src_kernel_win_0_va_7_fu_1253_p3;
        src_kernel_win_0_va_3_fu_246 <= src_kernel_win_0_va_2_fu_242;
        src_kernel_win_0_va_4_fu_250 <= src_kernel_win_0_va_8_fu_1271_p3;
        src_kernel_win_0_va_5_fu_254 <= src_kernel_win_0_va_4_fu_250;
        src_kernel_win_0_va_fu_234 <= src_kernel_win_0_va_6_fu_1235_p3;
        src_kernel_win_1_va_1_fu_262 <= src_kernel_win_1_va_fu_258;
        src_kernel_win_1_va_2_fu_266 <= src_kernel_win_1_va_7_fu_1500_p3;
        src_kernel_win_1_va_3_fu_270 <= src_kernel_win_1_va_2_fu_266;
        src_kernel_win_1_va_4_fu_274 <= src_kernel_win_1_va_8_fu_1518_p3;
        src_kernel_win_1_va_5_fu_278 <= src_kernel_win_1_va_4_fu_274;
        src_kernel_win_1_va_fu_258 <= src_kernel_win_1_va_6_fu_1482_p3;
        src_kernel_win_2_va_1_fu_286 <= src_kernel_win_2_va_fu_282;
        src_kernel_win_2_va_2_fu_290 <= src_kernel_win_2_va_10_fu_1729_p3;
        src_kernel_win_2_va_3_fu_294 <= src_kernel_win_2_va_2_fu_290;
        src_kernel_win_2_va_4_fu_298 <= src_kernel_win_2_va_11_fu_1747_p3;
        src_kernel_win_2_va_5_fu_302 <= src_kernel_win_2_va_4_fu_298;
        src_kernel_win_2_va_fu_282 <= src_kernel_win_2_va_9_fu_1711_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_reg_2570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        src_kernel_win_0_va_7_reg_2659 <= src_kernel_win_0_va_7_fu_1253_p3;
        src_kernel_win_1_va_7_reg_2685 <= src_kernel_win_1_va_7_fu_1500_p3;
        src_kernel_win_2_va_10_reg_2711 <= src_kernel_win_2_va_10_fu_1729_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((or_cond_i_reg_2619 == 1'd1) & (exitcond_reg_2570 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum2_reg_2665 <= sum2_fu_1327_p2;
        sum4_reg_2691 <= sum4_fu_1574_p2;
        sum5_reg_2717 <= sum5_fu_1803_p2;
        tmp10_reg_2680 <= tmp10_fu_1351_p2;
        tmp17_reg_2696 <= tmp17_fu_1580_p2;
        tmp18_reg_2701 <= tmp18_fu_1592_p2;
        tmp21_reg_2706 <= tmp21_fu_1598_p2;
        tmp28_reg_2722 <= tmp28_fu_1809_p2;
        tmp29_reg_2727 <= tmp29_fu_1821_p2;
        tmp32_reg_2732 <= tmp32_fu_1827_p2;
        tmp6_reg_2670 <= tmp6_fu_1333_p2;
        tmp7_reg_2675 <= tmp7_fu_1345_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_condition_pp0_exit_iter1_state5 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter1_state5 = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((exitcond1_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond1_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_3_ce0 = 1'b1;
    end else begin
        k_buf_0_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1)))) begin
        k_buf_0_val_3_ce1 = 1'b1;
    end else begin
        k_buf_0_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1)))) begin
        k_buf_0_val_3_we1 = 1'b1;
    end else begin
        k_buf_0_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_4_ce0 = 1'b1;
    end else begin
        k_buf_0_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_117_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1)))) begin
        k_buf_0_val_4_ce1 = 1'b1;
    end else begin
        k_buf_0_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op229_read_state5 == 1'b1)) begin
            k_buf_0_val_4_d1 = k_buf_0_val_3_q0;
        end else if ((1'b1 == ap_condition_554)) begin
            k_buf_0_val_4_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_117_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1)))) begin
        k_buf_0_val_4_we1 = 1'b1;
    end else begin
        k_buf_0_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_0_val_5_ce0 = 1'b1;
    end else begin
        k_buf_0_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1)))) begin
        k_buf_0_val_5_ce1 = 1'b1;
    end else begin
        k_buf_0_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op229_read_state5 == 1'b1)) begin
            k_buf_0_val_5_d1 = k_buf_0_val_4_q0;
        end else if ((1'b1 == ap_condition_548)) begin
            k_buf_0_val_5_d1 = p_src_data_stream_0_V_dout;
        end else begin
            k_buf_0_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_0_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1)))) begin
        k_buf_0_val_5_we1 = 1'b1;
    end else begin
        k_buf_0_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_3_ce0 = 1'b1;
    end else begin
        k_buf_1_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1)))) begin
        k_buf_1_val_3_ce1 = 1'b1;
    end else begin
        k_buf_1_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1)))) begin
        k_buf_1_val_3_we1 = 1'b1;
    end else begin
        k_buf_1_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_4_ce0 = 1'b1;
    end else begin
        k_buf_1_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_117_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1)))) begin
        k_buf_1_val_4_ce1 = 1'b1;
    end else begin
        k_buf_1_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op287_read_state5 == 1'b1)) begin
            k_buf_1_val_4_d1 = k_buf_1_val_3_q0;
        end else if ((1'b1 == ap_condition_554)) begin
            k_buf_1_val_4_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_117_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1)))) begin
        k_buf_1_val_4_we1 = 1'b1;
    end else begin
        k_buf_1_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_1_val_5_ce0 = 1'b1;
    end else begin
        k_buf_1_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1)))) begin
        k_buf_1_val_5_ce1 = 1'b1;
    end else begin
        k_buf_1_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op287_read_state5 == 1'b1)) begin
            k_buf_1_val_5_d1 = k_buf_1_val_4_q0;
        end else if ((1'b1 == ap_condition_548)) begin
            k_buf_1_val_5_d1 = p_src_data_stream_1_V_dout;
        end else begin
            k_buf_1_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_1_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1)))) begin
        k_buf_1_val_5_we1 = 1'b1;
    end else begin
        k_buf_1_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_3_ce0 = 1'b1;
    end else begin
        k_buf_2_val_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1)))) begin
        k_buf_2_val_3_ce1 = 1'b1;
    end else begin
        k_buf_2_val_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1)))) begin
        k_buf_2_val_3_we1 = 1'b1;
    end else begin
        k_buf_2_val_3_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_4_ce0 = 1'b1;
    end else begin
        k_buf_2_val_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_117_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1)))) begin
        k_buf_2_val_4_ce1 = 1'b1;
    end else begin
        k_buf_2_val_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op339_read_state5 == 1'b1)) begin
            k_buf_2_val_4_d1 = k_buf_2_val_3_q0;
        end else if ((1'b1 == ap_condition_554)) begin
            k_buf_2_val_4_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_4_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_4_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_117_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1)))) begin
        k_buf_2_val_4_we1 = 1'b1;
    end else begin
        k_buf_2_val_4_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        k_buf_2_val_5_ce0 = 1'b1;
    end else begin
        k_buf_2_val_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1)))) begin
        k_buf_2_val_5_ce1 = 1'b1;
    end else begin
        k_buf_2_val_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_62)) begin
        if ((ap_predicate_op339_read_state5 == 1'b1)) begin
            k_buf_2_val_5_d1 = k_buf_2_val_4_q0;
        end else if ((1'b1 == ap_condition_548)) begin
            k_buf_2_val_5_d1 = p_src_data_stream_2_V_dout;
        end else begin
            k_buf_2_val_5_d1 = 'bx;
        end
    end else begin
        k_buf_2_val_5_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1)))) begin
        k_buf_2_val_5_we1 = 1'b1;
    end else begin
        k_buf_2_val_5_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_0_V_blk_n = p_dst_data_stream_0_V_full_n;
    end else begin
        p_dst_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_0_V_write = 1'b1;
    end else begin
        p_dst_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_1_V_blk_n = p_dst_data_stream_1_V_full_n;
    end else begin
        p_dst_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_1_V_write = 1'b1;
    end else begin
        p_dst_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_dst_data_stream_2_V_blk_n = p_dst_data_stream_2_V_full_n;
    end else begin
        p_dst_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_dst_data_stream_2_V_write = 1'b1;
    end else begin
        p_dst_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (exitcond_reg_2570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_0_V_blk_n = p_src_data_stream_0_V_empty_n;
    end else begin
        p_src_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op229_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op217_read_state5 == 1'b1)))) begin
        p_src_data_stream_0_V_read = 1'b1;
    end else begin
        p_src_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (exitcond_reg_2570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_1_V_blk_n = p_src_data_stream_1_V_empty_n;
    end else begin
        p_src_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op287_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op275_read_state5 == 1'b1)))) begin
        p_src_data_stream_1_V_read = 1'b1;
    end else begin
        p_src_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((((or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (exitcond_reg_2570 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_data_stream_2_V_blk_n = p_src_data_stream_2_V_empty_n;
    end else begin
        p_src_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op339_read_state5 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_predicate_op330_read_state5 == 1'b1)))) begin
        p_src_data_stream_2_V_read = 1'b1;
    end else begin
        p_src_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_7_fu_615_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond1_fu_625_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ImagLoc_x_fu_983_p2 = ($signed(12'd4095) + $signed(t_V_2_cast_fu_951_p1));

assign OP1_V_0_2_cast_fu_1313_p1 = src_kernel_win_0_va_1_fu_238;

assign OP1_V_0_cast_fu_1287_p1 = src_kernel_win_0_va_5_fu_254;

assign OP1_V_1_2_cast_fu_1560_p1 = src_kernel_win_1_va_1_fu_262;

assign OP1_V_1_cast_fu_1534_p1 = src_kernel_win_1_va_5_fu_278;

assign OP1_V_2_2_cast_fu_1789_p1 = src_kernel_win_2_va_1_fu_286;

assign OP1_V_2_cast_fu_1763_p1 = src_kernel_win_2_va_5_fu_302;

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op339_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op330_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op287_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op275_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op217_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op339_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op330_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op287_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op275_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op217_read_state5 == 1'b1)))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter2 == 1'b1) & (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)))) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op339_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op330_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op287_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op275_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op217_read_state5 == 1'b1)))));
end

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state5_pp0_stage0_iter1 = (((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op339_read_state5 == 1'b1)) | ((p_src_data_stream_2_V_empty_n == 1'b0) & (ap_predicate_op330_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op287_read_state5 == 1'b1)) | ((p_src_data_stream_1_V_empty_n == 1'b0) & (ap_predicate_op275_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op229_read_state5 == 1'b1)) | ((p_src_data_stream_0_V_empty_n == 1'b0) & (ap_predicate_op217_read_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter2 = (((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_2_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_1_V_full_n == 1'b0)) | ((or_cond_i_reg_2619_pp0_iter1_reg == 1'd1) & (p_dst_data_stream_0_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_condition_548 = ((tmp_9_reg_2524 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0));
end

always @ (*) begin
    ap_condition_554 = ((tmp_117_0_1_reg_2528 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0));
end

always @ (*) begin
    ap_condition_62 = ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

always @ (*) begin
    ap_predicate_op217_read_state5 = ((or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0));
end

always @ (*) begin
    ap_predicate_op229_read_state5 = ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (exitcond_reg_2570 == 1'd0));
end

always @ (*) begin
    ap_predicate_op275_read_state5 = ((or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0));
end

always @ (*) begin
    ap_predicate_op287_read_state5 = ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (exitcond_reg_2570 == 1'd0));
end

always @ (*) begin
    ap_predicate_op330_read_state5 = ((or_cond_i_i_reg_2579 == 1'd1) & (icmp_reg_2519 == 1'd0) & (exitcond_reg_2570 == 1'd0));
end

always @ (*) begin
    ap_predicate_op339_read_state5 = ((tmp_1_reg_2510 == 1'd1) & (icmp_reg_2519 == 1'd1) & (or_cond_i_i_reg_2579 == 1'd1) & (exitcond_reg_2570 == 1'd0));
end

assign brmerge_fu_1073_p2 = (tmp_73_0_0_not_reg_2514 | tmp_17_fu_1003_p2);

assign col_assign_2_0_t_fu_1123_p2 = (tmp_67_reg_2583 ^ 2'd3);

assign col_buf_0_val_0_0_fu_1140_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_0_val_3_q0 : tmp_26_fu_1128_p5);

assign col_buf_0_val_1_0_fu_1159_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_0_val_4_q0 : tmp_27_fu_1147_p5);

assign col_buf_0_val_2_0_fu_1178_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_0_val_5_q0 : tmp_28_fu_1166_p5);

assign col_buf_1_val_0_0_fu_1387_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_1_val_3_q0 : tmp_42_fu_1375_p5);

assign col_buf_1_val_1_0_fu_1406_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_1_val_4_q0 : tmp_43_fu_1394_p5);

assign col_buf_1_val_2_0_fu_1425_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_1_val_5_q0 : tmp_44_fu_1413_p5);

assign col_buf_2_val_0_0_fu_1625_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_2_val_3_q0 : tmp_57_fu_1613_p5);

assign col_buf_2_val_1_0_fu_1644_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_2_val_4_q0 : tmp_58_fu_1632_p5);

assign col_buf_2_val_2_0_fu_1663_p3 = ((brmerge_reg_2588[0:0] === 1'b1) ? k_buf_2_val_5_q0 : tmp_59_fu_1651_p5);

assign exitcond1_fu_625_p2 = ((t_V_reg_587 == 11'd1052) ? 1'b1 : 1'b0);

assign exitcond_fu_955_p2 = ((t_V_2_reg_598 == 11'd1682) ? 1'b1 : 1'b0);

assign i_V_fu_631_p2 = (t_V_reg_587 + 11'd1);

assign icmp1_fu_977_p2 = ((tmp_63_fu_967_p4 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_fu_659_p2 = ((tmp_fu_649_p4 != 10'd0) ? 1'b1 : 1'b0);

assign isneg_1_fu_2095_p3 = p_Val2_5_fu_2089_p2[32'd10];

assign isneg_2_fu_2202_p3 = p_Val2_s_fu_2196_p2[32'd10];

assign isneg_fu_1988_p3 = p_Val2_2_fu_1982_p2[32'd10];

assign j_V_fu_961_p2 = (t_V_2_reg_598 + 11'd1);

assign k_buf_0_val_3_address0 = tmp_25_fu_1078_p1;

assign k_buf_0_val_4_address0 = tmp_25_fu_1078_p1;

assign k_buf_0_val_5_address0 = tmp_25_fu_1078_p1;

assign k_buf_1_val_3_address0 = tmp_25_fu_1078_p1;

assign k_buf_1_val_4_address0 = tmp_25_fu_1078_p1;

assign k_buf_1_val_5_address0 = tmp_25_fu_1078_p1;

assign k_buf_2_val_3_address0 = tmp_25_fu_1078_p1;

assign k_buf_2_val_4_address0 = tmp_25_fu_1078_p1;

assign k_buf_2_val_5_address0 = tmp_25_fu_1078_p1;

assign not_i_i_i1_fu_2129_p2 = ((tmp_55_fu_2113_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i2_fu_2236_p2 = ((tmp_65_fu_2220_p4 != 3'd0) ? 1'b1 : 1'b0);

assign not_i_i_i_fu_2022_p2 = ((tmp_40_fu_2006_p4 != 3'd0) ? 1'b1 : 1'b0);

assign or_cond_i412_i_fu_709_p2 = (tmp_4_fu_703_p2 & rev_fu_697_p2);

assign or_cond_i_fu_1091_p2 = (icmp_reg_2519 & icmp1_fu_977_p2);

assign or_cond_i_i_fu_1009_p2 = (tmp_17_fu_1003_p2 & rev1_fu_997_p2);

assign overflow_1_fu_2135_p2 = (tmp_i_i1_fu_2123_p2 & not_i_i_i1_fu_2129_p2);

assign overflow_2_fu_2242_p2 = (tmp_i_i2_fu_2230_p2 & not_i_i_i2_fu_2236_p2);

assign overflow_fu_2028_p2 = (tmp_i_i_fu_2016_p2 & not_i_i_i_fu_2022_p2);

assign p_Val2_1_fu_2001_p2 = (tmp7_reg_2675 + tmp9_fu_1996_p2);

assign p_Val2_2_fu_1982_p2 = (tmp5_cast_fu_1978_p1 - sum40_cast_fu_1966_p1);

assign p_Val2_3_fu_2108_p2 = (tmp18_reg_2701 + tmp20_fu_2103_p2);

assign p_Val2_5_fu_2089_p2 = (tmp16_cast_fu_2085_p1 - sum37_cast_fu_2073_p1);

assign p_Val2_6_fu_2215_p2 = (tmp29_reg_2727 + tmp31_fu_2210_p2);

assign p_Val2_s_fu_2196_p2 = (tmp27_cast_fu_2192_p1 - sum34_cast_fu_2180_p1);

assign p_assign_1_fu_1023_p2 = (12'd1 - t_V_2_cast_fu_951_p1);

assign p_assign_2_fu_1043_p2 = ($signed(12'd3358) - $signed(p_p2_i_i_fu_1029_p3));

assign p_assign_6_0_1_fu_753_p2 = ($signed(12'd4094) + $signed(t_V_cast_fu_621_p1));

assign p_assign_6_0_2_fu_779_p2 = ($signed(12'd4093) + $signed(t_V_cast_fu_621_p1));

assign p_assign_7_fu_723_p2 = (12'd1 - t_V_cast_fu_621_p1);

assign p_assign_8_fu_743_p2 = ($signed(12'd2098) - $signed(p_p2_i413_i_fu_729_p3));

assign p_dst_data_stream_0_V_din = ((tmp_i_i_72_fu_2042_p2[0:0] === 1'b1) ? p_mux_i_i_cast_fu_2034_p3 : p_Val2_1_fu_2001_p2);

assign p_dst_data_stream_1_V_din = ((tmp_i_i1_73_fu_2149_p2[0:0] === 1'b1) ? p_mux_i_i1_cast_fu_2141_p3 : p_Val2_3_fu_2108_p2);

assign p_dst_data_stream_2_V_din = ((tmp_i_i2_74_fu_2256_p2[0:0] === 1'b1) ? p_mux_i_i2_cast_fu_2248_p3 : p_Val2_6_fu_2215_p2);

assign p_mux_i_i1_cast_fu_2141_p3 = ((tmp_i_i1_fu_2123_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i2_cast_fu_2248_p3 = ((tmp_i_i2_fu_2230_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_mux_i_i_cast_fu_2034_p3 = ((tmp_i_i_fu_2016_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign p_p2_i413_i_fu_729_p3 = ((tmp_11_fu_715_p3[0:0] === 1'b1) ? p_assign_7_fu_723_p2 : tmp_3_fu_683_p2);

assign p_p2_i_i_fu_1029_p3 = ((tmp_66_fu_1015_p3[0:0] === 1'b1) ? p_assign_1_fu_1023_p2 : ImagLoc_x_fu_983_p2);

assign p_p2_i_i_p_assign_2_fu_1049_p3 = ((tmp_23_fu_1037_p2[0:0] === 1'b1) ? p_p2_i_i_fu_1029_p3 : p_assign_2_fu_1043_p2);

assign p_shl1_cast_fu_1550_p1 = p_shl1_fu_1542_p3;

assign p_shl1_fu_1542_p3 = {{src_kernel_win_1_va_3_fu_270}, {1'd0}};

assign p_shl2_cast_fu_1779_p1 = p_shl2_fu_1771_p3;

assign p_shl2_fu_1771_p3 = {{src_kernel_win_2_va_3_fu_294}, {1'd0}};

assign p_shl_cast_fu_1303_p1 = p_shl_fu_1295_p3;

assign p_shl_fu_1295_p3 = {{src_kernel_win_0_va_3_fu_246}, {1'd0}};

assign r_V_7_0_1_2_fu_1950_p3 = {{src_kernel_win_0_va_7_reg_2659}, {1'd0}};

assign r_V_7_1_1_2_fu_2057_p3 = {{src_kernel_win_1_va_7_reg_2685}, {1'd0}};

assign r_V_7_2_1_2_fu_2164_p3 = {{src_kernel_win_2_va_10_reg_2711}, {1'd0}};

assign rev1_fu_997_p2 = (tmp_64_fu_989_p3 ^ 1'd1);

assign rev_fu_697_p2 = (tmp_10_fu_689_p3 ^ 1'd1);

assign row_assign_9_0_1_t_fu_875_p2 = (2'd1 - tmp_32_fu_867_p3);

assign row_assign_9_0_2_t_fu_913_p2 = (2'd1 - tmp_36_fu_905_p3);

assign row_assign_9_1_0_t_fu_945_p2 = (2'd1 - tmp_49_fu_937_p3);

assign row_assign_9_fu_837_p2 = (2'd1 - tmp_39_fu_829_p3);

assign src_kernel_win_0_va_6_fu_1235_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_29_fu_1224_p5 : col_buf_0_val_0_0_fu_1140_p3);

assign src_kernel_win_0_va_7_fu_1253_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_33_fu_1242_p5 : col_buf_0_val_1_0_fu_1159_p3);

assign src_kernel_win_0_va_8_fu_1271_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_37_fu_1260_p5 : col_buf_0_val_2_0_fu_1178_p3);

assign src_kernel_win_1_va_6_fu_1482_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_50_fu_1471_p5 : col_buf_1_val_0_0_fu_1387_p3);

assign src_kernel_win_1_va_7_fu_1500_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_51_fu_1489_p5 : col_buf_1_val_1_0_fu_1406_p3);

assign src_kernel_win_1_va_8_fu_1518_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_52_fu_1507_p5 : col_buf_1_val_2_0_fu_1425_p3);

assign src_kernel_win_2_va_10_fu_1729_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_61_fu_1718_p5 : col_buf_2_val_1_0_fu_1644_p3);

assign src_kernel_win_2_va_11_fu_1747_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_62_fu_1736_p5 : col_buf_2_val_2_0_fu_1663_p3);

assign src_kernel_win_2_va_9_fu_1711_p3 = ((tmp_2_reg_2532[0:0] === 1'b1) ? tmp_60_fu_1700_p5 : col_buf_2_val_0_0_fu_1625_p3);

assign sum1_fu_1321_p2 = (p_shl_cast_fu_1303_p1 + OP1_V_0_2_cast_fu_1313_p1);

assign sum2_fu_1327_p2 = (OP1_V_0_cast_fu_1287_p1 + sum1_fu_1321_p2);

assign sum34_cast_fu_2180_p1 = sum5_reg_2717;

assign sum37_cast_fu_2073_p1 = sum4_reg_2691;

assign sum3_fu_1568_p2 = (p_shl1_cast_fu_1550_p1 + OP1_V_1_2_cast_fu_1560_p1);

assign sum40_cast_fu_1966_p1 = sum2_reg_2665;

assign sum4_fu_1574_p2 = (OP1_V_1_cast_fu_1534_p1 + sum3_fu_1568_p2);

assign sum5_fu_1803_p2 = (OP1_V_2_cast_fu_1763_p1 + sum_fu_1797_p2);

assign sum_fu_1797_p2 = (p_shl2_cast_fu_1779_p1 + OP1_V_2_2_cast_fu_1789_p1);

assign t_V_2_cast_fu_951_p1 = t_V_2_reg_598;

assign t_V_cast_fu_621_p1 = t_V_reg_587;

assign tmp10_fu_1351_p2 = (src_kernel_win_0_va_6_fu_1235_p3 - src_kernel_win_0_va_1_fu_238);

assign tmp16_cast_fu_2085_p1 = tmp16_fu_2079_p2;

assign tmp16_fu_2079_p2 = (tmp_161_1_1_cast_fu_2064_p1 + tmp17_cast_fu_2076_p1);

assign tmp17_cast_fu_2076_p1 = tmp17_reg_2696;

assign tmp17_fu_1580_p2 = (tmp_161_1_2_2_cast_fu_1564_p1 + tmp_161_1_0_2_cast_fu_1538_p1);

assign tmp18_fu_1592_p2 = (tmp19_fu_1586_p2 - src_kernel_win_1_va_5_fu_278);

assign tmp19_fu_1586_p2 = (src_kernel_win_1_va_8_fu_1518_p3 - tmp_76_fu_1554_p2);

assign tmp20_fu_2103_p2 = (tmp_77_fu_2068_p2 + tmp21_reg_2706);

assign tmp21_fu_1598_p2 = (src_kernel_win_1_va_6_fu_1482_p3 - src_kernel_win_1_va_1_fu_262);

assign tmp27_cast_fu_2192_p1 = tmp27_fu_2186_p2;

assign tmp27_fu_2186_p2 = (tmp_161_2_1_cast_fu_2171_p1 + tmp28_cast_fu_2183_p1);

assign tmp28_cast_fu_2183_p1 = tmp28_reg_2722;

assign tmp28_fu_1809_p2 = (tmp_161_2_2_2_cast_fu_1793_p1 + tmp_161_2_0_2_cast_fu_1767_p1);

assign tmp29_fu_1821_p2 = (tmp30_fu_1815_p2 - src_kernel_win_2_va_5_fu_302);

assign tmp30_fu_1815_p2 = (src_kernel_win_2_va_11_fu_1747_p3 - tmp_82_fu_1783_p2);

assign tmp31_fu_2210_p2 = (tmp_83_fu_2175_p2 + tmp32_reg_2732);

assign tmp32_fu_1827_p2 = (src_kernel_win_2_va_9_fu_1711_p3 - src_kernel_win_2_va_1_fu_286);

assign tmp5_cast_fu_1978_p1 = tmp5_fu_1972_p2;

assign tmp5_fu_1972_p2 = (tmp_161_0_1_cast_fu_1957_p1 + tmp6_cast_fu_1969_p1);

assign tmp6_cast_fu_1969_p1 = tmp6_reg_2670;

assign tmp6_fu_1333_p2 = (tmp_161_0_2_2_cast_fu_1317_p1 + tmp_161_0_0_2_cast_fu_1291_p1);

assign tmp7_fu_1345_p2 = (tmp8_fu_1339_p2 - src_kernel_win_0_va_5_fu_254);

assign tmp8_fu_1339_p2 = (src_kernel_win_0_va_8_fu_1271_p3 - tmp_70_fu_1307_p2);

assign tmp9_fu_1996_p2 = (tmp_71_fu_1961_p2 + tmp10_reg_2680);

assign tmp_10_fu_689_p3 = tmp_3_fu_683_p2[32'd11];

assign tmp_117_0_1_fu_671_p2 = ((t_V_reg_587 == 11'd0) ? 1'b1 : 1'b0);

assign tmp_11_fu_715_p3 = tmp_3_fu_683_p2[32'd11];

assign tmp_12_fu_749_p1 = t_V_reg_587[1:0];

assign tmp_13_fu_759_p3 = p_assign_6_0_1_fu_753_p2[32'd11];

assign tmp_15_fu_767_p3 = p_assign_6_0_1_fu_753_p2[32'd11];

assign tmp_161_0_0_2_cast_fu_1291_p1 = src_kernel_win_0_va_8_fu_1271_p3;

assign tmp_161_0_1_cast_fu_1957_p1 = r_V_7_0_1_2_fu_1950_p3;

assign tmp_161_0_2_2_cast_fu_1317_p1 = src_kernel_win_0_va_6_fu_1235_p3;

assign tmp_161_1_0_2_cast_fu_1538_p1 = src_kernel_win_1_va_8_fu_1518_p3;

assign tmp_161_1_1_cast_fu_2064_p1 = r_V_7_1_1_2_fu_2057_p3;

assign tmp_161_1_2_2_cast_fu_1564_p1 = src_kernel_win_1_va_6_fu_1482_p3;

assign tmp_161_2_0_2_cast_fu_1767_p1 = src_kernel_win_2_va_11_fu_1747_p3;

assign tmp_161_2_1_cast_fu_2171_p1 = r_V_7_2_1_2_fu_2164_p3;

assign tmp_161_2_2_2_cast_fu_1793_p1 = src_kernel_win_2_va_9_fu_1711_p3;

assign tmp_16_fu_775_p1 = t_V_reg_587[1:0];

assign tmp_17_fu_1003_p2 = (($signed(ImagLoc_x_fu_983_p2) < $signed(12'd1680)) ? 1'b1 : 1'b0);

assign tmp_18_fu_785_p3 = p_assign_6_0_2_fu_779_p2[32'd11];

assign tmp_19_fu_793_p3 = p_assign_6_0_2_fu_779_p2[32'd11];

assign tmp_1_fu_637_p2 = ((t_V_reg_587 < 11'd1050) ? 1'b1 : 1'b0);

assign tmp_20_fu_801_p1 = t_V_reg_587[1:0];

assign tmp_21_fu_805_p1 = p_p2_i413_i_fu_729_p3[1:0];

assign tmp_22_fu_843_p2 = (tmp_12_fu_749_p1 ^ 2'd2);

assign tmp_23_fu_1037_p2 = (($signed(p_p2_i_i_fu_1029_p3) < $signed(12'd1680)) ? 1'b1 : 1'b0);

assign tmp_24_fu_809_p1 = tmp_3_fu_683_p2[1:0];

assign tmp_25_fu_1078_p1 = $unsigned(x_cast_fu_1065_p1);

assign tmp_2_fu_677_p2 = ((t_V_reg_587 > 11'd1050) ? 1'b1 : 1'b0);

assign tmp_30_fu_813_p1 = p_p2_i413_i_fu_729_p3[1:0];

assign tmp_31_fu_817_p1 = p_assign_8_fu_743_p2[1:0];

assign tmp_32_fu_867_p3 = ((tmp_13_fu_759_p3[0:0] === 1'b1) ? tmp_35_fu_859_p3 : tmp_22_fu_843_p2);

assign tmp_34_fu_881_p2 = (2'd1 + tmp_12_fu_749_p1);

assign tmp_35_fu_859_p3 = ((tmp_15_fu_767_p3[0:0] === 1'b1) ? tmp_41_fu_849_p2 : tmp_45_fu_855_p1);

assign tmp_36_fu_905_p3 = ((tmp_18_fu_785_p3[0:0] === 1'b1) ? tmp_54_fu_897_p3 : tmp_34_fu_881_p2);

assign tmp_38_fu_821_p3 = ((tmp_8_fu_737_p2[0:0] === 1'b1) ? tmp_30_fu_813_p1 : tmp_31_fu_817_p1);

assign tmp_39_fu_829_p3 = ((or_cond_i412_i_fu_709_p2[0:0] === 1'b1) ? tmp_24_fu_809_p1 : tmp_38_fu_821_p3);

assign tmp_3_fu_683_p2 = ($signed(12'd4095) + $signed(t_V_cast_fu_621_p1));

assign tmp_40_fu_2006_p4 = {{p_Val2_2_fu_1982_p2[10:8]}};

assign tmp_41_fu_849_p2 = ($signed(2'd2) - $signed(tmp_16_fu_775_p1));

assign tmp_45_fu_855_p1 = p_assign_6_0_1_fu_753_p2[1:0];

assign tmp_46_fu_919_p2 = ($signed(2'd2) - $signed(tmp_21_fu_805_p1));

assign tmp_47_fu_925_p3 = ((tmp_8_fu_737_p2[0:0] === 1'b1) ? tmp_21_fu_805_p1 : tmp_46_fu_919_p2);

assign tmp_48_fu_887_p2 = (tmp_20_fu_801_p1 ^ 2'd3);

assign tmp_49_fu_937_p3 = ((or_cond_i412_i_fu_709_p2[0:0] === 1'b1) ? tmp_56_fu_933_p1 : tmp_47_fu_925_p3);

assign tmp_4_fu_703_p2 = (($signed(tmp_3_fu_683_p2) < $signed(12'd1050)) ? 1'b1 : 1'b0);

assign tmp_53_fu_893_p1 = p_assign_6_0_2_fu_779_p2[1:0];

assign tmp_54_fu_897_p3 = ((tmp_19_fu_793_p3[0:0] === 1'b1) ? tmp_48_fu_887_p2 : tmp_53_fu_893_p1);

assign tmp_55_fu_2113_p4 = {{p_Val2_5_fu_2089_p2[10:8]}};

assign tmp_56_fu_933_p1 = tmp_3_fu_683_p2[1:0];

assign tmp_63_fu_967_p4 = {{t_V_2_reg_598[10:1]}};

assign tmp_64_fu_989_p3 = ImagLoc_x_fu_983_p2[32'd11];

assign tmp_65_fu_2220_p4 = {{p_Val2_s_fu_2196_p2[10:8]}};

assign tmp_66_fu_1015_p3 = ImagLoc_x_fu_983_p2[32'd11];

assign tmp_67_fu_1069_p1 = x_fu_1057_p3[1:0];

assign tmp_6_fu_609_p2 = (tmp_5_reg_576 + 2'd1);

assign tmp_70_fu_1307_p2 = src_kernel_win_0_va_3_fu_246 << 8'd1;

assign tmp_71_fu_1961_p2 = src_kernel_win_0_va_7_reg_2659 << 8'd1;

assign tmp_73_0_0_not_fu_643_p2 = (tmp_1_fu_637_p2 ^ 1'd1);

assign tmp_76_fu_1554_p2 = src_kernel_win_1_va_3_fu_270 << 8'd1;

assign tmp_77_fu_2068_p2 = src_kernel_win_1_va_7_reg_2685 << 8'd1;

assign tmp_7_fu_615_p2 = ((tmp_5_reg_576 == 2'd2) ? 1'b1 : 1'b0);

assign tmp_82_fu_1783_p2 = src_kernel_win_2_va_3_fu_294 << 8'd1;

assign tmp_83_fu_2175_p2 = src_kernel_win_2_va_10_reg_2711 << 8'd1;

assign tmp_8_fu_737_p2 = (($signed(p_p2_i413_i_fu_729_p3) < $signed(12'd1050)) ? 1'b1 : 1'b0);

assign tmp_9_fu_665_p2 = ((t_V_reg_587 == 11'd1) ? 1'b1 : 1'b0);

assign tmp_fu_649_p4 = {{t_V_reg_587[10:1]}};

assign tmp_i_i1_73_fu_2149_p2 = (overflow_1_fu_2135_p2 | isneg_1_fu_2095_p3);

assign tmp_i_i1_fu_2123_p2 = (isneg_1_fu_2095_p3 ^ 1'd1);

assign tmp_i_i2_74_fu_2256_p2 = (overflow_2_fu_2242_p2 | isneg_2_fu_2202_p3);

assign tmp_i_i2_fu_2230_p2 = (isneg_2_fu_2202_p3 ^ 1'd1);

assign tmp_i_i_72_fu_2042_p2 = (overflow_fu_2028_p2 | isneg_fu_1988_p3);

assign tmp_i_i_fu_2016_p2 = (isneg_fu_1988_p3 ^ 1'd1);

assign x_cast_fu_1065_p1 = x_fu_1057_p3;

assign x_fu_1057_p3 = ((or_cond_i_i_fu_1009_p2[0:0] === 1'b1) ? ImagLoc_x_fu_983_p2 : p_p2_i_i_p_assign_2_fu_1049_p3);

endmodule //Filter2D
