// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xsubsamble.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XSubsamble_CfgInitialize(XSubsamble *InstancePtr, XSubsamble_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->Axilites_r_BaseAddress = ConfigPtr->Axilites_r_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XSubsamble_Set_ram(XSubsamble *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSubsamble_WriteReg(InstancePtr->Axilites_BaseAddress, XSUBSAMBLE_AXILITES_ADDR_RAM_DATA, Data);
}

u32 XSubsamble_Get_ram(XSubsamble *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSubsamble_ReadReg(InstancePtr->Axilites_BaseAddress, XSUBSAMBLE_AXILITES_ADDR_RAM_DATA);
    return Data;
}

void XSubsamble_Set_n(XSubsamble *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XSubsamble_WriteReg(InstancePtr->Axilites_r_BaseAddress, XSUBSAMBLE_AXILITES_R_ADDR_N_DATA, Data);
}

u32 XSubsamble_Get_n(XSubsamble *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XSubsamble_ReadReg(InstancePtr->Axilites_r_BaseAddress, XSUBSAMBLE_AXILITES_R_ADDR_N_DATA);
    return Data;
}

