#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_start", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_done", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_idle", 1, hls_out, -1, "", "", 1),
	Port_Property("ap_ready", 1, hls_out, -1, "", "", 1),
	Port_Property("stream_in_TDATA", 24, hls_in, 0, "axis", "in_data", 1),
	Port_Property("stream_in_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("stream_in_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("stream_in_TKEEP", 3, hls_in, 1, "axis", "in_data", 1),
	Port_Property("stream_in_TSTRB", 3, hls_in, 2, "axis", "in_data", 1),
	Port_Property("stream_in_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("stream_in_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("stream_in_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("stream_in_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("stream_process_TDATA", 24, hls_out, 7, "axis", "out_data", 1),
	Port_Property("stream_process_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("stream_process_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
	Port_Property("stream_process_TKEEP", 3, hls_out, 8, "axis", "out_data", 1),
	Port_Property("stream_process_TSTRB", 3, hls_out, 9, "axis", "out_data", 1),
	Port_Property("stream_process_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("stream_process_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("stream_process_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("stream_process_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("stream_passThrough_TDATA", 24, hls_out, 14, "axis", "out_data", 1),
	Port_Property("stream_passThrough_TVALID", 1, hls_out, 20, "axis", "out_vld", 1),
	Port_Property("stream_passThrough_TREADY", 1, hls_in, 20, "axis", "out_acc", 1),
	Port_Property("stream_passThrough_TKEEP", 3, hls_out, 15, "axis", "out_data", 1),
	Port_Property("stream_passThrough_TSTRB", 3, hls_out, 16, "axis", "out_data", 1),
	Port_Property("stream_passThrough_TUSER", 1, hls_out, 17, "axis", "out_data", 1),
	Port_Property("stream_passThrough_TLAST", 1, hls_out, 18, "axis", "out_data", 1),
	Port_Property("stream_passThrough_TID", 1, hls_out, 19, "axis", "out_data", 1),
	Port_Property("stream_passThrough_TDEST", 1, hls_out, 20, "axis", "out_data", 1),
};
const char* HLS_Design_Meta::dut_name = "subsamble";
