webtalk_init -webtalk_dir /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-03-06 09:15:37" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174131719_174131720_210618149_329" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "j6pfdc98evv6te09qoh4aa7hb4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_56" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "56" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3902.937 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.618 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1551863669000" -context "sdk\\\\bsp/1551863669000"
webtalk_add_data -client sdk -key hwid -value "1549536825000" -context "sdk\\\\bsp/1551863669000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1551863669000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1551863669000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1551863669000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1551863737671"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1551863737671"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1551863737671"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1551863737671"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1551863737671"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1551863737671"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1551863737671"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1551863737671"
webtalk_transmit -clientid 1750773123 -regid "174131719_174131720_210618149_329" -xml /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
