webtalk_init -webtalk_dir /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-01-31 14:03:02" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "174131719_174131720_210618149_329" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "p7n7mbb2f39v5t1ksmqca25otk" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "12" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3381.736 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.671 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1548942715000" -context "sdk\\\\bsp/1548942715000"
webtalk_add_data -client sdk -key hwid -value "1548677722000" -context "sdk\\\\bsp/1548942715000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1548942715000"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1548942715000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1548942715000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1548943382486"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1548943382486"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1548943382486"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1548943382486"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1548943382486"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1548943382486"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1548943382486"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1548943382486"
webtalk_transmit -clientid 4220394811 -regid "174131719_174131720_210618149_329" -xml /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/userfs/q/qj544/w2k/QLight/vivado/proj/HDMI.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
