// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x10 : Data signal of ap_return
//        bit 31~0 - ap_return[31:0] (Read)
// 0x18 : Data signal of ram
//        bit 31~0 - ram[31:0] (Read/Write)
// 0x1c : reserved
// 0x20 : Data signal of length_r
//        bit 31~0 - length_r[31:0] (Read/Write)
// 0x24 : reserved
// 0x28 : Data signal of height
//        bit 31~0 - height[31:0] (Read/Write)
// 0x2c : reserved
// 0x30 : Data signal of r
//        bit 31~0 - r[31:0] (Read)
// 0x34 : Control signal of r
//        bit 0  - r_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of g
//        bit 31~0 - g[31:0] (Read)
// 0x3c : Control signal of g
//        bit 0  - g_ap_vld (Read/COR)
//        others - reserved
// 0x40 : Data signal of b
//        bit 31~0 - b[31:0] (Read)
// 0x44 : Control signal of b
//        bit 0  - b_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XTOPLEVEL_AXILITES_ADDR_AP_CTRL       0x00
#define XTOPLEVEL_AXILITES_ADDR_GIE           0x04
#define XTOPLEVEL_AXILITES_ADDR_IER           0x08
#define XTOPLEVEL_AXILITES_ADDR_ISR           0x0c
#define XTOPLEVEL_AXILITES_ADDR_AP_RETURN     0x10
#define XTOPLEVEL_AXILITES_BITS_AP_RETURN     32
#define XTOPLEVEL_AXILITES_ADDR_RAM_DATA      0x18
#define XTOPLEVEL_AXILITES_BITS_RAM_DATA      32
#define XTOPLEVEL_AXILITES_ADDR_LENGTH_R_DATA 0x20
#define XTOPLEVEL_AXILITES_BITS_LENGTH_R_DATA 32
#define XTOPLEVEL_AXILITES_ADDR_HEIGHT_DATA   0x28
#define XTOPLEVEL_AXILITES_BITS_HEIGHT_DATA   32
#define XTOPLEVEL_AXILITES_ADDR_R_DATA        0x30
#define XTOPLEVEL_AXILITES_BITS_R_DATA        32
#define XTOPLEVEL_AXILITES_ADDR_R_CTRL        0x34
#define XTOPLEVEL_AXILITES_ADDR_G_DATA        0x38
#define XTOPLEVEL_AXILITES_BITS_G_DATA        32
#define XTOPLEVEL_AXILITES_ADDR_G_CTRL        0x3c
#define XTOPLEVEL_AXILITES_ADDR_B_DATA        0x40
#define XTOPLEVEL_AXILITES_BITS_B_DATA        32
#define XTOPLEVEL_AXILITES_ADDR_B_CTRL        0x44

